// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/data.dart';
import 'api/project.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DTOColumnRole dco_decode_dto_column_role(dynamic raw);

  @protected
  DTODataColumn dco_decode_dto_data_column(dynamic raw);

  @protected
  DTODataTable dco_decode_dto_data_table(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<DTODataColumn> dco_decode_list_dto_data_column(dynamic raw);

  @protected
  List<DTODataTable> dco_decode_list_dto_data_table(dynamic raw);

  @protected
  List<Point2D> dco_decode_list_point_2_d(dynamic raw);

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<ProjectNode> dco_decode_list_project_node(dynamic raw);

  @protected
  NodeType dco_decode_node_type(dynamic raw);

  @protected
  Point2D dco_decode_point_2_d(dynamic raw);

  @protected
  ProjectNode dco_decode_project_node(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DTOColumnRole sse_decode_dto_column_role(SseDeserializer deserializer);

  @protected
  DTODataColumn sse_decode_dto_data_column(SseDeserializer deserializer);

  @protected
  DTODataTable sse_decode_dto_data_table(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<DTODataColumn> sse_decode_list_dto_data_column(
    SseDeserializer deserializer,
  );

  @protected
  List<DTODataTable> sse_decode_list_dto_data_table(
    SseDeserializer deserializer,
  );

  @protected
  List<Point2D> sse_decode_list_point_2_d(SseDeserializer deserializer);

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<ProjectNode> sse_decode_list_project_node(SseDeserializer deserializer);

  @protected
  NodeType sse_decode_node_type(SseDeserializer deserializer);

  @protected
  Point2D sse_decode_point_2_d(SseDeserializer deserializer);

  @protected
  ProjectNode sse_decode_project_node(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_dto_column_role(DTOColumnRole self, SseSerializer serializer);

  @protected
  void sse_encode_dto_data_column(DTODataColumn self, SseSerializer serializer);

  @protected
  void sse_encode_dto_data_table(DTODataTable self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_dto_data_column(
    List<DTODataColumn> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_dto_data_table(
    List<DTODataTable> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_point_2_d(List<Point2D> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_project_node(
    List<ProjectNode> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_node_type(NodeType self, SseSerializer serializer);

  @protected
  void sse_encode_point_2_d(Point2D self, SseSerializer serializer);

  @protected
  void sse_encode_project_node(ProjectNode self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
