// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/data.dart';
import 'api/project.dart';
import 'api/properties.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => 1788347686;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_frontend',
        ioDirectory: '../backend/crates/plot_bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  ProjectNode crateApiProjectAddEmptyTable({
    required String parentId,
    required String name,
    required BigInt rowCount,
    required BigInt colCount,
  });

  ProjectNode crateApiProjectAddProjectNode({
    required String parentId,
    required String name,
    required NodeType nodeType,
  });

  ProjectNode crateApiProjectAddTableFromRaw({
    required String parentId,
    required String raw,
    required String displayName,
  });

  bool crateApiDataApplyScatterRule({required BigInt rowCount});

  ProjectNode crateApiProjectDeleteProjectNode({required String nodeId});

  Future<FolderProperties> crateApiPropertiesFolderPropertiesDefault();

  Future<FunctionProperties> crateApiPropertiesFunctionPropertiesDefault();

  DTODataTable crateApiDataGetEmptyTableData();

  FolderProperties crateApiPropertiesGetFolderProperties({
    required String nodeId,
  });

  FunctionProperties crateApiPropertiesGetFunctionProperties({
    required String nodeId,
  });

  GraphProperties crateApiPropertiesGetGraphProperties({
    required String nodeId,
  });

  DTODataTable crateApiDataGetInitialTableData();

  List<Point2D> crateApiDataGetMockScientificData({required BigInt numPoints});

  DTODataTable crateApiDataGetNewTableData({
    required BigInt rowCount,
    required BigInt colCount,
  });

  ProjectNode crateApiProjectGetProjectTree();

  ShapeProperties crateApiPropertiesGetShapeProperties({
    required String nodeId,
  });

  DTODataTable crateApiProjectGetTable({required String tableId});

  TableProperties crateApiPropertiesGetTableProperties({
    required String nodeId,
  });

  List<DTODataTable> crateApiProjectGetTablesForGraph({
    required String graphId,
  });

  Future<GraphProperties> crateApiPropertiesGraphPropertiesDefault();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  ProjectNode crateApiProjectMoveProjectNode({
    required String nodeId,
    required String newParentId,
  });

  DTODataTable crateApiDataParseClipboardTable({required String raw});

  ProjectNode crateApiProjectRenameProjectNode({
    required String nodeId,
    required String newName,
  });

  ProjectNode crateApiProjectReorderProjectChildren({
    required String parentId,
    required BigInt oldIndex,
    required BigInt newIndex,
  });

  void crateApiProjectSaveTable({
    required String tableId,
    required List<DTODataColumn> columns,
  });

  void crateApiPropertiesSetFolderProperties({
    required String nodeId,
    required FolderProperties props,
  });

  void crateApiPropertiesSetFunctionProperties({
    required String nodeId,
    required FunctionProperties props,
  });

  void crateApiPropertiesSetGraphProperties({
    required String nodeId,
    required GraphProperties props,
  });

  void crateApiPropertiesSetShapeProperties({
    required String nodeId,
    required ShapeProperties props,
  });

  void crateApiPropertiesSetTableProperties({
    required String nodeId,
    required TableProperties props,
  });

  Future<ShapeProperties> crateApiPropertiesShapePropertiesDefault();

  Future<TableProperties> crateApiPropertiesTablePropertiesDefault();

  void crateApiProjectUpdateTableFromRaw({
    required String tableId,
    required String raw,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  ProjectNode crateApiProjectAddEmptyTable({
    required String parentId,
    required String name,
    required BigInt rowCount,
    required BigInt colCount,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(parentId, serializer);
          sse_encode_String(name, serializer);
          sse_encode_usize(rowCount, serializer);
          sse_encode_usize(colCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectAddEmptyTableConstMeta,
        argValues: [parentId, name, rowCount, colCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectAddEmptyTableConstMeta =>
      const TaskConstMeta(
        debugName: "add_empty_table",
        argNames: ["parentId", "name", "rowCount", "colCount"],
      );

  @override
  ProjectNode crateApiProjectAddProjectNode({
    required String parentId,
    required String name,
    required NodeType nodeType,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(parentId, serializer);
          sse_encode_String(name, serializer);
          sse_encode_node_type(nodeType, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectAddProjectNodeConstMeta,
        argValues: [parentId, name, nodeType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectAddProjectNodeConstMeta =>
      const TaskConstMeta(
        debugName: "add_project_node",
        argNames: ["parentId", "name", "nodeType"],
      );

  @override
  ProjectNode crateApiProjectAddTableFromRaw({
    required String parentId,
    required String raw,
    required String displayName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(parentId, serializer);
          sse_encode_String(raw, serializer);
          sse_encode_String(displayName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectAddTableFromRawConstMeta,
        argValues: [parentId, raw, displayName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectAddTableFromRawConstMeta =>
      const TaskConstMeta(
        debugName: "add_table_from_raw",
        argNames: ["parentId", "raw", "displayName"],
      );

  @override
  bool crateApiDataApplyScatterRule({required BigInt rowCount}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(rowCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDataApplyScatterRuleConstMeta,
        argValues: [rowCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDataApplyScatterRuleConstMeta =>
      const TaskConstMeta(
        debugName: "apply_scatter_rule",
        argNames: ["rowCount"],
      );

  @override
  ProjectNode crateApiProjectDeleteProjectNode({required String nodeId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectDeleteProjectNodeConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectDeleteProjectNodeConstMeta =>
      const TaskConstMeta(
        debugName: "delete_project_node",
        argNames: ["nodeId"],
      );

  @override
  Future<FolderProperties> crateApiPropertiesFolderPropertiesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_folder_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesFolderPropertiesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesFolderPropertiesDefaultConstMeta =>
      const TaskConstMeta(debugName: "folder_properties_default", argNames: []);

  @override
  Future<FunctionProperties> crateApiPropertiesFunctionPropertiesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_function_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesFunctionPropertiesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesFunctionPropertiesDefaultConstMeta =>
      const TaskConstMeta(
        debugName: "function_properties_default",
        argNames: [],
      );

  @override
  DTODataTable crateApiDataGetEmptyTableData() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dto_data_table,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDataGetEmptyTableDataConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDataGetEmptyTableDataConstMeta =>
      const TaskConstMeta(debugName: "get_empty_table_data", argNames: []);

  @override
  FolderProperties crateApiPropertiesGetFolderProperties({
    required String nodeId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_folder_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesGetFolderPropertiesConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesGetFolderPropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "get_folder_properties",
        argNames: ["nodeId"],
      );

  @override
  FunctionProperties crateApiPropertiesGetFunctionProperties({
    required String nodeId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_function_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesGetFunctionPropertiesConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesGetFunctionPropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "get_function_properties",
        argNames: ["nodeId"],
      );

  @override
  GraphProperties crateApiPropertiesGetGraphProperties({
    required String nodeId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_graph_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesGetGraphPropertiesConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesGetGraphPropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "get_graph_properties",
        argNames: ["nodeId"],
      );

  @override
  DTODataTable crateApiDataGetInitialTableData() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dto_data_table,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDataGetInitialTableDataConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDataGetInitialTableDataConstMeta =>
      const TaskConstMeta(debugName: "get_initial_table_data", argNames: []);

  @override
  List<Point2D> crateApiDataGetMockScientificData({required BigInt numPoints}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(numPoints, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 13)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_point_2_d,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDataGetMockScientificDataConstMeta,
        argValues: [numPoints],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDataGetMockScientificDataConstMeta =>
      const TaskConstMeta(
        debugName: "get_mock_scientific_data",
        argNames: ["numPoints"],
      );

  @override
  DTODataTable crateApiDataGetNewTableData({
    required BigInt rowCount,
    required BigInt colCount,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_usize(rowCount, serializer);
          sse_encode_usize(colCount, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dto_data_table,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDataGetNewTableDataConstMeta,
        argValues: [rowCount, colCount],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDataGetNewTableDataConstMeta =>
      const TaskConstMeta(
        debugName: "get_new_table_data",
        argNames: ["rowCount", "colCount"],
      );

  @override
  ProjectNode crateApiProjectGetProjectTree() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectGetProjectTreeConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectGetProjectTreeConstMeta =>
      const TaskConstMeta(debugName: "get_project_tree", argNames: []);

  @override
  ShapeProperties crateApiPropertiesGetShapeProperties({
    required String nodeId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_shape_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesGetShapePropertiesConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesGetShapePropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "get_shape_properties",
        argNames: ["nodeId"],
      );

  @override
  DTODataTable crateApiProjectGetTable({required String tableId}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tableId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dto_data_table,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectGetTableConstMeta,
        argValues: [tableId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectGetTableConstMeta =>
      const TaskConstMeta(debugName: "get_table", argNames: ["tableId"]);

  @override
  TableProperties crateApiPropertiesGetTableProperties({
    required String nodeId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_table_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesGetTablePropertiesConstMeta,
        argValues: [nodeId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesGetTablePropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "get_table_properties",
        argNames: ["nodeId"],
      );

  @override
  List<DTODataTable> crateApiProjectGetTablesForGraph({
    required String graphId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(graphId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 19)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_dto_data_table,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectGetTablesForGraphConstMeta,
        argValues: [graphId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectGetTablesForGraphConstMeta =>
      const TaskConstMeta(
        debugName: "get_tables_for_graph",
        argNames: ["graphId"],
      );

  @override
  Future<GraphProperties> crateApiPropertiesGraphPropertiesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 20,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_graph_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesGraphPropertiesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesGraphPropertiesDefaultConstMeta =>
      const TaskConstMeta(debugName: "graph_properties_default", argNames: []);

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 21)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 22,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  ProjectNode crateApiProjectMoveProjectNode({
    required String nodeId,
    required String newParentId,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_String(newParentId, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 23)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectMoveProjectNodeConstMeta,
        argValues: [nodeId, newParentId],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectMoveProjectNodeConstMeta =>
      const TaskConstMeta(
        debugName: "move_project_node",
        argNames: ["nodeId", "newParentId"],
      );

  @override
  DTODataTable crateApiDataParseClipboardTable({required String raw}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 24)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dto_data_table,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiDataParseClipboardTableConstMeta,
        argValues: [raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiDataParseClipboardTableConstMeta =>
      const TaskConstMeta(
        debugName: "parse_clipboard_table",
        argNames: ["raw"],
      );

  @override
  ProjectNode crateApiProjectRenameProjectNode({
    required String nodeId,
    required String newName,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_String(newName, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 25)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectRenameProjectNodeConstMeta,
        argValues: [nodeId, newName],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectRenameProjectNodeConstMeta =>
      const TaskConstMeta(
        debugName: "rename_project_node",
        argNames: ["nodeId", "newName"],
      );

  @override
  ProjectNode crateApiProjectReorderProjectChildren({
    required String parentId,
    required BigInt oldIndex,
    required BigInt newIndex,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(parentId, serializer);
          sse_encode_usize(oldIndex, serializer);
          sse_encode_usize(newIndex, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 26)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_project_node,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectReorderProjectChildrenConstMeta,
        argValues: [parentId, oldIndex, newIndex],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectReorderProjectChildrenConstMeta =>
      const TaskConstMeta(
        debugName: "reorder_project_children",
        argNames: ["parentId", "oldIndex", "newIndex"],
      );

  @override
  void crateApiProjectSaveTable({
    required String tableId,
    required List<DTODataColumn> columns,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tableId, serializer);
          sse_encode_list_dto_data_column(columns, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 27)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectSaveTableConstMeta,
        argValues: [tableId, columns],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectSaveTableConstMeta => const TaskConstMeta(
    debugName: "save_table",
    argNames: ["tableId", "columns"],
  );

  @override
  void crateApiPropertiesSetFolderProperties({
    required String nodeId,
    required FolderProperties props,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_box_autoadd_folder_properties(props, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 28)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesSetFolderPropertiesConstMeta,
        argValues: [nodeId, props],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesSetFolderPropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "set_folder_properties",
        argNames: ["nodeId", "props"],
      );

  @override
  void crateApiPropertiesSetFunctionProperties({
    required String nodeId,
    required FunctionProperties props,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_box_autoadd_function_properties(props, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 29)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesSetFunctionPropertiesConstMeta,
        argValues: [nodeId, props],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesSetFunctionPropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "set_function_properties",
        argNames: ["nodeId", "props"],
      );

  @override
  void crateApiPropertiesSetGraphProperties({
    required String nodeId,
    required GraphProperties props,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_box_autoadd_graph_properties(props, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 30)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesSetGraphPropertiesConstMeta,
        argValues: [nodeId, props],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesSetGraphPropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "set_graph_properties",
        argNames: ["nodeId", "props"],
      );

  @override
  void crateApiPropertiesSetShapeProperties({
    required String nodeId,
    required ShapeProperties props,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_box_autoadd_shape_properties(props, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 31)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesSetShapePropertiesConstMeta,
        argValues: [nodeId, props],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesSetShapePropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "set_shape_properties",
        argNames: ["nodeId", "props"],
      );

  @override
  void crateApiPropertiesSetTableProperties({
    required String nodeId,
    required TableProperties props,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(nodeId, serializer);
          sse_encode_box_autoadd_table_properties(props, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 32)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesSetTablePropertiesConstMeta,
        argValues: [nodeId, props],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesSetTablePropertiesConstMeta =>
      const TaskConstMeta(
        debugName: "set_table_properties",
        argNames: ["nodeId", "props"],
      );

  @override
  Future<ShapeProperties> crateApiPropertiesShapePropertiesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 33,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_shape_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesShapePropertiesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesShapePropertiesDefaultConstMeta =>
      const TaskConstMeta(debugName: "shape_properties_default", argNames: []);

  @override
  Future<TableProperties> crateApiPropertiesTablePropertiesDefault() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 34,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_table_properties,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiPropertiesTablePropertiesDefaultConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiPropertiesTablePropertiesDefaultConstMeta =>
      const TaskConstMeta(debugName: "table_properties_default", argNames: []);

  @override
  void crateApiProjectUpdateTableFromRaw({
    required String tableId,
    required String raw,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(tableId, serializer);
          sse_encode_String(raw, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 35)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiProjectUpdateTableFromRawConstMeta,
        argValues: [tableId, raw],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiProjectUpdateTableFromRawConstMeta =>
      const TaskConstMeta(
        debugName: "update_table_from_raw",
        argNames: ["tableId", "raw"],
      );

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FolderProperties dco_decode_box_autoadd_folder_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_folder_properties(raw);
  }

  @protected
  FunctionProperties dco_decode_box_autoadd_function_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_function_properties(raw);
  }

  @protected
  GraphProperties dco_decode_box_autoadd_graph_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_graph_properties(raw);
  }

  @protected
  ShapeProperties dco_decode_box_autoadd_shape_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_shape_properties(raw);
  }

  @protected
  TableProperties dco_decode_box_autoadd_table_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_table_properties(raw);
  }

  @protected
  DTOColumnRole dco_decode_dto_column_role(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return DTOColumnRole.values[raw as int];
  }

  @protected
  DTODataColumn dco_decode_dto_data_column(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DTODataColumn(
      name: dco_decode_String(arr[0]),
      role: dco_decode_dto_column_role(arr[1]),
      data: dco_decode_list_prim_f_64_strict(arr[2]),
    );
  }

  @protected
  DTODataTable dco_decode_dto_data_table(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return DTODataTable(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      columns: dco_decode_list_dto_data_column(arr[2]),
    );
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  FolderProperties dco_decode_folder_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FolderProperties(information: dco_decode_String(arr[0]));
  }

  @protected
  FunctionProperties dco_decode_function_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return FunctionProperties(equation: dco_decode_String(arr[0]));
  }

  @protected
  GraphProperties dco_decode_graph_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14)
      throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return GraphProperties(
      xMin: dco_decode_opt_box_autoadd_f_64(arr[0]),
      xMax: dco_decode_opt_box_autoadd_f_64(arr[1]),
      yMin: dco_decode_opt_box_autoadd_f_64(arr[2]),
      yMax: dco_decode_opt_box_autoadd_f_64(arr[3]),
      xVisible: dco_decode_bool(arr[4]),
      yVisible: dco_decode_bool(arr[5]),
      xScale: dco_decode_String(arr[6]),
      yScale: dco_decode_String(arr[7]),
      xLabel: dco_decode_String(arr[8]),
      yLabel: dco_decode_String(arr[9]),
      aspectRatio: dco_decode_opt_box_autoadd_f_64(arr[10]),
      showGrid: dco_decode_bool(arr[11]),
      showLegend: dco_decode_bool(arr[12]),
      legendPosition: dco_decode_String(arr[13]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<DTODataColumn> dco_decode_list_dto_data_column(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dto_data_column).toList();
  }

  @protected
  List<DTODataTable> dco_decode_list_dto_data_table(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_dto_data_table).toList();
  }

  @protected
  List<Point2D> dco_decode_list_point_2_d(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_point_2_d).toList();
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<ProjectNode> dco_decode_list_project_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_project_node).toList();
  }

  @protected
  NodeType dco_decode_node_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return NodeType.values[raw as int];
  }

  @protected
  double? dco_decode_opt_box_autoadd_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_f_64(raw);
  }

  @protected
  Point2D dco_decode_point_2_d(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return Point2D(x: dco_decode_f_64(arr[0]), y: dco_decode_f_64(arr[1]));
  }

  @protected
  ProjectNode dco_decode_project_node(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return ProjectNode(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      nodeType: dco_decode_node_type(arr[2]),
      children: dco_decode_list_project_node(arr[3]),
    );
  }

  @protected
  ShapeProperties dco_decode_shape_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 1)
      throw Exception('unexpected arr length: expect 1 but see ${arr.length}');
    return ShapeProperties(shapeType: dco_decode_String(arr[0]));
  }

  @protected
  TableProperties dco_decode_table_properties(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return TableProperties(
      legendDisplayName: dco_decode_String(arr[0]),
      lineStyle: dco_decode_String(arr[1]),
      lineThickness: dco_decode_f_64(arr[2]),
      lineVisible: dco_decode_bool(arr[3]),
      markerType: dco_decode_String(arr[4]),
      markerVisible: dco_decode_bool(arr[5]),
      lineColor: dco_decode_String(arr[6]),
      markerColor: dco_decode_String(arr[7]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_f_64(deserializer));
  }

  @protected
  FolderProperties sse_decode_box_autoadd_folder_properties(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_folder_properties(deserializer));
  }

  @protected
  FunctionProperties sse_decode_box_autoadd_function_properties(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_function_properties(deserializer));
  }

  @protected
  GraphProperties sse_decode_box_autoadd_graph_properties(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_graph_properties(deserializer));
  }

  @protected
  ShapeProperties sse_decode_box_autoadd_shape_properties(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_shape_properties(deserializer));
  }

  @protected
  TableProperties sse_decode_box_autoadd_table_properties(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_table_properties(deserializer));
  }

  @protected
  DTOColumnRole sse_decode_dto_column_role(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return DTOColumnRole.values[inner];
  }

  @protected
  DTODataColumn sse_decode_dto_data_column(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_name = sse_decode_String(deserializer);
    var var_role = sse_decode_dto_column_role(deserializer);
    var var_data = sse_decode_list_prim_f_64_strict(deserializer);
    return DTODataColumn(name: var_name, role: var_role, data: var_data);
  }

  @protected
  DTODataTable sse_decode_dto_data_table(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_columns = sse_decode_list_dto_data_column(deserializer);
    return DTODataTable(id: var_id, name: var_name, columns: var_columns);
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  FolderProperties sse_decode_folder_properties(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_information = sse_decode_String(deserializer);
    return FolderProperties(information: var_information);
  }

  @protected
  FunctionProperties sse_decode_function_properties(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_equation = sse_decode_String(deserializer);
    return FunctionProperties(equation: var_equation);
  }

  @protected
  GraphProperties sse_decode_graph_properties(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_xMin = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_xMax = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_yMin = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_yMax = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_xVisible = sse_decode_bool(deserializer);
    var var_yVisible = sse_decode_bool(deserializer);
    var var_xScale = sse_decode_String(deserializer);
    var var_yScale = sse_decode_String(deserializer);
    var var_xLabel = sse_decode_String(deserializer);
    var var_yLabel = sse_decode_String(deserializer);
    var var_aspectRatio = sse_decode_opt_box_autoadd_f_64(deserializer);
    var var_showGrid = sse_decode_bool(deserializer);
    var var_showLegend = sse_decode_bool(deserializer);
    var var_legendPosition = sse_decode_String(deserializer);
    return GraphProperties(
      xMin: var_xMin,
      xMax: var_xMax,
      yMin: var_yMin,
      yMax: var_yMax,
      xVisible: var_xVisible,
      yVisible: var_yVisible,
      xScale: var_xScale,
      yScale: var_yScale,
      xLabel: var_xLabel,
      yLabel: var_yLabel,
      aspectRatio: var_aspectRatio,
      showGrid: var_showGrid,
      showLegend: var_showLegend,
      legendPosition: var_legendPosition,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<DTODataColumn> sse_decode_list_dto_data_column(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DTODataColumn>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dto_data_column(deserializer));
    }
    return ans_;
  }

  @protected
  List<DTODataTable> sse_decode_list_dto_data_table(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <DTODataTable>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_dto_data_table(deserializer));
    }
    return ans_;
  }

  @protected
  List<Point2D> sse_decode_list_point_2_d(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Point2D>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_point_2_d(deserializer));
    }
    return ans_;
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<ProjectNode> sse_decode_list_project_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <ProjectNode>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_project_node(deserializer));
    }
    return ans_;
  }

  @protected
  NodeType sse_decode_node_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return NodeType.values[inner];
  }

  @protected
  double? sse_decode_opt_box_autoadd_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_f_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Point2D sse_decode_point_2_d(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_x = sse_decode_f_64(deserializer);
    var var_y = sse_decode_f_64(deserializer);
    return Point2D(x: var_x, y: var_y);
  }

  @protected
  ProjectNode sse_decode_project_node(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_nodeType = sse_decode_node_type(deserializer);
    var var_children = sse_decode_list_project_node(deserializer);
    return ProjectNode(
      id: var_id,
      name: var_name,
      nodeType: var_nodeType,
      children: var_children,
    );
  }

  @protected
  ShapeProperties sse_decode_shape_properties(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_shapeType = sse_decode_String(deserializer);
    return ShapeProperties(shapeType: var_shapeType);
  }

  @protected
  TableProperties sse_decode_table_properties(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_legendDisplayName = sse_decode_String(deserializer);
    var var_lineStyle = sse_decode_String(deserializer);
    var var_lineThickness = sse_decode_f_64(deserializer);
    var var_lineVisible = sse_decode_bool(deserializer);
    var var_markerType = sse_decode_String(deserializer);
    var var_markerVisible = sse_decode_bool(deserializer);
    var var_lineColor = sse_decode_String(deserializer);
    var var_markerColor = sse_decode_String(deserializer);
    return TableProperties(
      legendDisplayName: var_legendDisplayName,
      lineStyle: var_lineStyle,
      lineThickness: var_lineThickness,
      lineVisible: var_lineVisible,
      markerType: var_markerType,
      markerVisible: var_markerVisible,
      lineColor: var_lineColor,
      markerColor: var_markerColor,
    );
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_folder_properties(
    FolderProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_folder_properties(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_function_properties(
    FunctionProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_function_properties(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_graph_properties(
    GraphProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_graph_properties(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_shape_properties(
    ShapeProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_shape_properties(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_table_properties(
    TableProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_table_properties(self, serializer);
  }

  @protected
  void sse_encode_dto_column_role(
    DTOColumnRole self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_dto_data_column(
    DTODataColumn self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.name, serializer);
    sse_encode_dto_column_role(self.role, serializer);
    sse_encode_list_prim_f_64_strict(self.data, serializer);
  }

  @protected
  void sse_encode_dto_data_table(DTODataTable self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_list_dto_data_column(self.columns, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_folder_properties(
    FolderProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.information, serializer);
  }

  @protected
  void sse_encode_function_properties(
    FunctionProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.equation, serializer);
  }

  @protected
  void sse_encode_graph_properties(
    GraphProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_box_autoadd_f_64(self.xMin, serializer);
    sse_encode_opt_box_autoadd_f_64(self.xMax, serializer);
    sse_encode_opt_box_autoadd_f_64(self.yMin, serializer);
    sse_encode_opt_box_autoadd_f_64(self.yMax, serializer);
    sse_encode_bool(self.xVisible, serializer);
    sse_encode_bool(self.yVisible, serializer);
    sse_encode_String(self.xScale, serializer);
    sse_encode_String(self.yScale, serializer);
    sse_encode_String(self.xLabel, serializer);
    sse_encode_String(self.yLabel, serializer);
    sse_encode_opt_box_autoadd_f_64(self.aspectRatio, serializer);
    sse_encode_bool(self.showGrid, serializer);
    sse_encode_bool(self.showLegend, serializer);
    sse_encode_String(self.legendPosition, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_dto_data_column(
    List<DTODataColumn> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dto_data_column(item, serializer);
    }
  }

  @protected
  void sse_encode_list_dto_data_table(
    List<DTODataTable> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_dto_data_table(item, serializer);
    }
  }

  @protected
  void sse_encode_list_point_2_d(List<Point2D> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_point_2_d(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
    Float64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_project_node(
    List<ProjectNode> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_project_node(item, serializer);
    }
  }

  @protected
  void sse_encode_node_type(NodeType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_f_64(double? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_f_64(self, serializer);
    }
  }

  @protected
  void sse_encode_point_2_d(Point2D self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_f_64(self.x, serializer);
    sse_encode_f_64(self.y, serializer);
  }

  @protected
  void sse_encode_project_node(ProjectNode self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_node_type(self.nodeType, serializer);
    sse_encode_list_project_node(self.children, serializer);
  }

  @protected
  void sse_encode_shape_properties(
    ShapeProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.shapeType, serializer);
  }

  @protected
  void sse_encode_table_properties(
    TableProperties self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.legendDisplayName, serializer);
    sse_encode_String(self.lineStyle, serializer);
    sse_encode_f_64(self.lineThickness, serializer);
    sse_encode_bool(self.lineVisible, serializer);
    sse_encode_String(self.markerType, serializer);
    sse_encode_bool(self.markerVisible, serializer);
    sse_encode_String(self.lineColor, serializer);
    sse_encode_String(self.markerColor, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
