// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `detect_delimiter`, `normalise_cell`, `row_is_header`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`

/// Fetches a high-performance mock scientific dataset from the core math engine.
List<Point2D> getMockScientificData({required BigInt numPoints}) => RustLib
    .instance
    .api
    .crateApiDataGetMockScientificData(numPoints: numPoints);

/// Returns an empty two-column table (Position/X, Intensity/Y) with zero rows.
/// This is the canonical starting state of the application.
DTODataTable getEmptyTableData() =>
    RustLib.instance.api.crateApiDataGetEmptyTableData();

/// Returns a new blank table with `col_count` columns and `row_count` rows.
/// Every cell is initialised to f64::NAN (empty sentinel).
/// Column 0 gets role X; all others get role Y.
DTODataTable getNewTableData({
  required BigInt rowCount,
  required BigInt colCount,
}) => RustLib.instance.api.crateApiDataGetNewTableData(
  rowCount: rowCount,
  colCount: colCount,
);

/// Compat alias – kept so the existing frb_generated.rs glue compiles until
/// `flutter_rust_bridge_codegen generate` is re-run.
DTODataTable getInitialTableData() =>
    RustLib.instance.api.crateApiDataGetInitialTableData();

/// Parses a raw clipboard string (TSV / CSV) into a DTODataTable.
///
/// - Blank cells become f64::NAN (empty cell sentinel).
/// - Decimal normalisation handles European and US formats automatically.
/// - If the first row is all non-numeric, it is treated as column headers.
/// - Column roles: col 0 → X, col 1 → Y, rest → Y.
DTODataTable parseClipboardTable({required String raw}) =>
    RustLib.instance.api.crateApiDataParseClipboardTable(raw: raw);

/// Returns `true` (Scatter enabled) when `row_count` ≤ 10, `false` (Hide) otherwise.
/// Rust is the single source of truth for this threshold rule.
bool applyScatterRule({required BigInt rowCount}) =>
    RustLib.instance.api.crateApiDataApplyScatterRule(rowCount: rowCount);

/// DTOs for Table Data
enum DTOColumnRole { x, y, xError, yError, text }

class DTODataColumn {
  final String name;
  final DTOColumnRole role;

  /// f64::NAN encodes an empty cell. The Flutter side checks `value.isNaN`.
  final Float64List data;

  const DTODataColumn({
    required this.name,
    required this.role,
    required this.data,
  });

  @override
  int get hashCode => name.hashCode ^ role.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DTODataColumn &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          role == other.role &&
          data == other.data;
}

class DTODataTable {
  final String id;
  final String name;
  final List<DTODataColumn> columns;

  const DTODataTable({
    required this.id,
    required this.name,
    required this.columns,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ columns.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DTODataTable &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          columns == other.columns;
}

/// A simple DTO for passing 2D points to Flutter.
/// Using #[frb(dart_metadata=...)] if we needed specific Dart names, but simple structs map cleanly.
class Point2D {
  final double x;
  final double y;

  const Point2D({required this.x, required this.y});

  @override
  int get hashCode => x.hashCode ^ y.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Point2D &&
          runtimeType == other.runtimeType &&
          x == other.x &&
          y == other.y;
}
