// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `check_delimiter`, `escape_field`, `format_cell`, `pick_xy`, `table_to_delimited`, `without_header`, `write_text`

/// Exports one dataset. Delimiter `","` (CSV) or tab (TSV).
void exportTableCsv({
  required String tableId,
  required String path,
  required String delimiter,
  required bool includeHeader,
}) => RustLib.instance.api.crateApiExportExportTableCsv(
  tableId: tableId,
  path: path,
  delimiter: delimiter,
  includeHeader: includeHeader,
);

/// Exports all curves under a graph as one interleaved file:
/// `X_<table>, Y_<table>, …` per dataset in tree order. Ragged tables are
/// padded with empty cells.
void exportGraphDataCsv({
  required String graphId,
  required String path,
  required String delimiter,
  required bool includeHeader,
}) => RustLib.instance.api.crateApiExportExportGraphDataCsv(
  graphId: graphId,
  path: path,
  delimiter: delimiter,
  includeHeader: includeHeader,
);
