// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Cheap syntax check for inspector feedback (no sampling).
void validateFunctionExpression({required String expr}) => RustLib.instance.api
    .crateApiFunctionsValidateFunctionExpression(expr: expr);

/// Samples the function node over its local domain override if set,
/// else over the visible viewport. Parse/domain errors propagate to Dart
/// (inspector shows them; the canvas skips the curve).
List<Point2D> getFunctionCurveData({
  required String nodeId,
  required double viewportXMin,
  required double viewportXMax,
}) => RustLib.instance.api.crateApiFunctionsGetFunctionCurveData(
  nodeId: nodeId,
  viewportXMin: viewportXMin,
  viewportXMax: viewportXMax,
);
