// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'project.dart';

// These functions are ignored because they are not marked as `pub`: `push_capped`, `redo_stack`, `restore_snapshot`, `snapshot_current`, `undo_stack`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `HistorySnapshot`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`

/// Records the pre-mutation state; clears the redo stack.
void checkpoint() => RustLib.instance.api.crateApiHistoryCheckpoint();

/// Restores the last checkpoint (current state moves to redo).
ProjectNode undo() => RustLib.instance.api.crateApiHistoryUndo();

/// Re-applies an undone state (current state moves back to undo).
ProjectNode redo() => RustLib.instance.api.crateApiHistoryRedo();

HistoryStatus historyStatus() =>
    RustLib.instance.api.crateApiHistoryHistoryStatus();

/// Button/FRB status (both fields drive UI enablement).
class HistoryStatus {
  final bool canUndo;
  final bool canRedo;

  const HistoryStatus({required this.canUndo, required this.canRedo});

  @override
  int get hashCode => canUndo.hashCode ^ canRedo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HistoryStatus &&
          runtimeType == other.runtimeType &&
          canUndo == other.canUndo &&
          canRedo == other.canRedo;
}
