// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `find_graph`, `init_curve_props`, `init_function_props`, `next_color_for_siblings`, `next_combined_color`, `palette_by_name`

/// Palette names for building UI buttons.
List<String> listPalettes() =>
    RustLib.instance.api.crateApiPalettesListPalettes();

/// Hex colors of one palette (for swatch previews). Err on unknown name.
List<String> paletteColors({required String palette}) =>
    RustLib.instance.api.crateApiPalettesPaletteColors(palette: palette);

/// Re-aligns a graph's curves to a palette: tree order → color sequence
/// (datasets and functions share one index, so deleting/reordering is fixed
/// with one tap). Custom single-curve tweaks are overwritten; other
/// properties are preserved.
void applyPalette({required String graphId, required String palette}) => RustLib
    .instance
    .api
    .crateApiPalettesApplyPalette(graphId: graphId, palette: palette);
