// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'project.dart';

// These functions are ignored because they are not marked as `pub`: `csv_to_table`, `default_role_for_index`, `escape_csv_field`, `find_node_name`, `format_cell`, `load_project_from_zip`, `new_now`, `parse_cell`, `parse_header_cell`, `read_json_file_optional`, `read_json_file`, `read_text_file`, `role_to_tag`, `save_project_to_zip`, `split_csv_line`, `table_to_csv`, `tag_to_role`, `write_json_file`, `write_text_file`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ProjectManifest`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Saves the current project to `path` (`.primeplot` zip bundle).
void saveProject({required String path}) =>
    RustLib.instance.api.crateApiPersistenceSaveProject(path: path);

/// Loads a `.primeplot` bundle from `path`, replacing all in-memory state.
/// Returns the restored project tree DTO on success.
ProjectNode loadProject({required String path}) =>
    RustLib.instance.api.crateApiPersistenceLoadProject(path: path);

/// Resets everything to the canonical empty project
/// (Workspace > Project > Graph > Table), clearing all property stores.
ProjectNode newProject() =>
    RustLib.instance.api.crateApiPersistenceNewProject();
