// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `default_theme`, `get_config_dir`, `get_prefs_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`

AppPreferences getPreferences() =>
    RustLib.instance.api.crateApiPrefsGetPreferences();

void setPreferences({required AppPreferences prefs}) =>
    RustLib.instance.api.crateApiPrefsSetPreferences(prefs: prefs);

class AppPreferences {
  final String theme;

  const AppPreferences({required this.theme});

  static Future<AppPreferences> default_() =>
      RustLib.instance.api.crateApiPrefsAppPreferencesDefault();

  @override
  int get hashCode => theme.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppPreferences &&
          runtimeType == other.runtimeType &&
          theme == other.theme;
}
