// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `dto_to_engine_table`, `generate_id`, `get_state`, `get_table_store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

ProjectNode getProjectTree() =>
    RustLib.instance.api.crateApiProjectGetProjectTree();

ProjectNode addProjectNode({
  required String parentId,
  required String name,
  required NodeType nodeType,
}) => RustLib.instance.api.crateApiProjectAddProjectNode(
  parentId: parentId,
  name: name,
  nodeType: nodeType,
);

ProjectNode moveProjectNode({
  required String nodeId,
  required String newParentId,
}) => RustLib.instance.api.crateApiProjectMoveProjectNode(
  nodeId: nodeId,
  newParentId: newParentId,
);

ProjectNode renameProjectNode({
  required String nodeId,
  required String newName,
}) => RustLib.instance.api.crateApiProjectRenameProjectNode(
  nodeId: nodeId,
  newName: newName,
);

ProjectNode reorderProjectChildren({
  required String parentId,
  required BigInt oldIndex,
  required BigInt newIndex,
}) => RustLib.instance.api.crateApiProjectReorderProjectChildren(
  parentId: parentId,
  oldIndex: oldIndex,
  newIndex: newIndex,
);

ProjectNode deleteProjectNode({required String nodeId}) =>
    RustLib.instance.api.crateApiProjectDeleteProjectNode(nodeId: nodeId);

void updateTableFromRaw({required String tableId, required String raw}) =>
    RustLib.instance.api.crateApiProjectUpdateTableFromRaw(
      tableId: tableId,
      raw: raw,
    );

void saveTable({
  required String tableId,
  required List<DTODataColumn> columns,
}) => RustLib.instance.api.crateApiProjectSaveTable(
  tableId: tableId,
  columns: columns,
);

ProjectNode addEmptyTable({
  required String parentId,
  required String name,
  required BigInt rowCount,
  required BigInt colCount,
}) => RustLib.instance.api.crateApiProjectAddEmptyTable(
  parentId: parentId,
  name: name,
  rowCount: rowCount,
  colCount: colCount,
);

ProjectNode addTableFromRaw({
  required String parentId,
  required String raw,
  required String displayName,
}) => RustLib.instance.api.crateApiProjectAddTableFromRaw(
  parentId: parentId,
  raw: raw,
  displayName: displayName,
);

DTODataTable getTable({required String tableId}) =>
    RustLib.instance.api.crateApiProjectGetTable(tableId: tableId);

List<DTODataTable> getTablesForGraph({required String graphId}) =>
    RustLib.instance.api.crateApiProjectGetTablesForGraph(graphId: graphId);

enum NodeType { folder, dataset, plot }

class ProjectNode {
  final String id;
  final String name;
  final NodeType nodeType;
  final List<ProjectNode> children;

  const ProjectNode({
    required this.id,
    required this.name,
    required this.nodeType,
    required this.children,
  });

  @override
  int get hashCode =>
      id.hashCode ^ name.hashCode ^ nodeType.hashCode ^ children.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectNode &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          nodeType == other.nodeType &&
          children == other.children;
}
