// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_folder_store`, `get_function_store`, `get_graph_store`, `get_shape_store`, `get_table_store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

FolderProperties getFolderProperties({required String nodeId}) =>
    RustLib.instance.api.crateApiPropertiesGetFolderProperties(nodeId: nodeId);

void setFolderProperties({
  required String nodeId,
  required FolderProperties props,
}) => RustLib.instance.api.crateApiPropertiesSetFolderProperties(
  nodeId: nodeId,
  props: props,
);

GraphProperties getGraphProperties({required String nodeId}) =>
    RustLib.instance.api.crateApiPropertiesGetGraphProperties(nodeId: nodeId);

void setGraphProperties({
  required String nodeId,
  required GraphProperties props,
}) => RustLib.instance.api.crateApiPropertiesSetGraphProperties(
  nodeId: nodeId,
  props: props,
);

TableProperties getTableProperties({required String nodeId}) =>
    RustLib.instance.api.crateApiPropertiesGetTableProperties(nodeId: nodeId);

void setTableProperties({
  required String nodeId,
  required TableProperties props,
}) => RustLib.instance.api.crateApiPropertiesSetTableProperties(
  nodeId: nodeId,
  props: props,
);

FunctionProperties getFunctionProperties({required String nodeId}) => RustLib
    .instance
    .api
    .crateApiPropertiesGetFunctionProperties(nodeId: nodeId);

void setFunctionProperties({
  required String nodeId,
  required FunctionProperties props,
}) => RustLib.instance.api.crateApiPropertiesSetFunctionProperties(
  nodeId: nodeId,
  props: props,
);

ShapeProperties getShapeProperties({required String nodeId}) =>
    RustLib.instance.api.crateApiPropertiesGetShapeProperties(nodeId: nodeId);

void setShapeProperties({
  required String nodeId,
  required ShapeProperties props,
}) => RustLib.instance.api.crateApiPropertiesSetShapeProperties(
  nodeId: nodeId,
  props: props,
);

class FolderProperties {
  final String information;

  const FolderProperties({required this.information});

  static Future<FolderProperties> default_() =>
      RustLib.instance.api.crateApiPropertiesFolderPropertiesDefault();

  @override
  int get hashCode => information.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FolderProperties &&
          runtimeType == other.runtimeType &&
          information == other.information;
}

class FunctionProperties {
  final String equation;

  const FunctionProperties({required this.equation});

  static Future<FunctionProperties> default_() =>
      RustLib.instance.api.crateApiPropertiesFunctionPropertiesDefault();

  @override
  int get hashCode => equation.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FunctionProperties &&
          runtimeType == other.runtimeType &&
          equation == other.equation;
}

class GraphProperties {
  final double? xMin;
  final double? xMax;
  final double? yMin;
  final double? yMax;
  final bool xVisible;
  final bool yVisible;
  final String xScale;
  final String yScale;
  final String xLabel;
  final String yLabel;
  final double? aspectRatio;
  final bool showGrid;
  final bool showLegend;
  final String legendPosition;

  const GraphProperties({
    this.xMin,
    this.xMax,
    this.yMin,
    this.yMax,
    required this.xVisible,
    required this.yVisible,
    required this.xScale,
    required this.yScale,
    required this.xLabel,
    required this.yLabel,
    this.aspectRatio,
    required this.showGrid,
    required this.showLegend,
    required this.legendPosition,
  });

  static Future<GraphProperties> default_() =>
      RustLib.instance.api.crateApiPropertiesGraphPropertiesDefault();

  @override
  int get hashCode =>
      xMin.hashCode ^
      xMax.hashCode ^
      yMin.hashCode ^
      yMax.hashCode ^
      xVisible.hashCode ^
      yVisible.hashCode ^
      xScale.hashCode ^
      yScale.hashCode ^
      xLabel.hashCode ^
      yLabel.hashCode ^
      aspectRatio.hashCode ^
      showGrid.hashCode ^
      showLegend.hashCode ^
      legendPosition.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is GraphProperties &&
          runtimeType == other.runtimeType &&
          xMin == other.xMin &&
          xMax == other.xMax &&
          yMin == other.yMin &&
          yMax == other.yMax &&
          xVisible == other.xVisible &&
          yVisible == other.yVisible &&
          xScale == other.xScale &&
          yScale == other.yScale &&
          xLabel == other.xLabel &&
          yLabel == other.yLabel &&
          aspectRatio == other.aspectRatio &&
          showGrid == other.showGrid &&
          showLegend == other.showLegend &&
          legendPosition == other.legendPosition;
}

class ShapeProperties {
  final String shapeType;

  const ShapeProperties({required this.shapeType});

  static Future<ShapeProperties> default_() =>
      RustLib.instance.api.crateApiPropertiesShapePropertiesDefault();

  @override
  int get hashCode => shapeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ShapeProperties &&
          runtimeType == other.runtimeType &&
          shapeType == other.shapeType;
}

class TableProperties {
  final String legendDisplayName;
  final String lineStyle;
  final double lineThickness;
  final bool lineVisible;
  final String markerType;
  final bool markerVisible;
  final String lineColor;
  final String markerColor;

  const TableProperties({
    required this.legendDisplayName,
    required this.lineStyle,
    required this.lineThickness,
    required this.lineVisible,
    required this.markerType,
    required this.markerVisible,
    required this.lineColor,
    required this.markerColor,
  });

  static Future<TableProperties> default_() =>
      RustLib.instance.api.crateApiPropertiesTablePropertiesDefault();

  @override
  int get hashCode =>
      legendDisplayName.hashCode ^
      lineStyle.hashCode ^
      lineThickness.hashCode ^
      lineVisible.hashCode ^
      markerType.hashCode ^
      markerVisible.hashCode ^
      lineColor.hashCode ^
      markerColor.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TableProperties &&
          runtimeType == other.runtimeType &&
          legendDisplayName == other.legendDisplayName &&
          lineStyle == other.lineStyle &&
          lineThickness == other.lineThickness &&
          lineVisible == other.lineVisible &&
          markerType == other.markerType &&
          markerVisible == other.markerVisible &&
          lineColor == other.lineColor &&
          markerColor == other.markerColor;
}
