// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'data.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `column_mut`, `map_column`, `stats_of`, `table_not_found`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`

/// `y_i = y_i + value`.
DTODataTable columnAddScalar({
  required String tableId,
  required BigInt colIndex,
  required double value,
}) => RustLib.instance.api.crateApiTransformsColumnAddScalar(
  tableId: tableId,
  colIndex: colIndex,
  value: value,
);

/// `y_i = y_i * value`.
DTODataTable columnMultiplyScalar({
  required String tableId,
  required BigInt colIndex,
  required double value,
}) => RustLib.instance.api.crateApiTransformsColumnMultiplyScalar(
  tableId: tableId,
  colIndex: colIndex,
  value: value,
);

/// Maps finite values to [0, 1]. Errors on empty/constant columns.
DTODataTable columnNormalize({
  required String tableId,
  required BigInt colIndex,
}) => RustLib.instance.api.crateApiTransformsColumnNormalize(
  tableId: tableId,
  colIndex: colIndex,
);

/// Evaluates a `meval` expression per cell with `y` = current value and
/// `i` = row index (e.g. `"y / 1000"`, `"y - 273.15"`, `"log10(y)"`).
DTODataTable columnApplyExpression({
  required String tableId,
  required BigInt colIndex,
  required String expr,
}) => RustLib.instance.api.crateApiTransformsColumnApplyExpression(
  tableId: tableId,
  colIndex: colIndex,
  expr: expr,
);

/// First 5 transformed values without mutating (dialog live preview).
Float64List previewColumnExpression({
  required String tableId,
  required BigInt colIndex,
  required String expr,
}) => RustLib.instance.api.crateApiTransformsPreviewColumnExpression(
  tableId: tableId,
  colIndex: colIndex,
  expr: expr,
);

/// Fills the column with `linspace(start, end)` over the current row count.
DTODataTable columnFillLinspace({
  required String tableId,
  required BigInt colIndex,
  required double start,
  required double end,
}) => RustLib.instance.api.crateApiTransformsColumnFillLinspace(
  tableId: tableId,
  colIndex: colIndex,
  start: start,
  end: end,
);

ColumnStatistics getColumnStatistics({
  required String tableId,
  required BigInt colIndex,
}) => RustLib.instance.api.crateApiTransformsGetColumnStatistics(
  tableId: tableId,
  colIndex: colIndex,
);

/// Aggregates one entry per dataset under a graph, in tree order.
/// Curves with no finite XY pairs are skipped.
List<SeriesStatistics> getGraphStatistics({required String graphId}) =>
    RustLib.instance.api.crateApiTransformsGetGraphStatistics(graphId: graphId);

/// Per-column summary statistics (finite values only, except `nan_count`).
class ColumnStatistics {
  final double min;
  final double max;
  final double mean;
  final double stdDev;
  final BigInt count;
  final BigInt nanCount;

  const ColumnStatistics({
    required this.min,
    required this.max,
    required this.mean,
    required this.stdDev,
    required this.count,
    required this.nanCount,
  });

  @override
  int get hashCode =>
      min.hashCode ^
      max.hashCode ^
      mean.hashCode ^
      stdDev.hashCode ^
      count.hashCode ^
      nanCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ColumnStatistics &&
          runtimeType == other.runtimeType &&
          min == other.min &&
          max == other.max &&
          mean == other.mean &&
          stdDev == other.stdDev &&
          count == other.count &&
          nanCount == other.nanCount;
}

/// Per-series extents for the canvas statistics HUD.
class SeriesStatistics {
  final String tableId;
  final String name;
  final double minX;
  final double maxX;
  final double minY;
  final double maxY;
  final BigInt nPoints;

  const SeriesStatistics({
    required this.tableId,
    required this.name,
    required this.minX,
    required this.maxX,
    required this.minY,
    required this.maxY,
    required this.nPoints,
  });

  @override
  int get hashCode =>
      tableId.hashCode ^
      name.hashCode ^
      minX.hashCode ^
      maxX.hashCode ^
      minY.hashCode ^
      maxY.hashCode ^
      nPoints.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SeriesStatistics &&
          runtimeType == other.runtimeType &&
          tableId == other.tableId &&
          name == other.name &&
          minX == other.minX &&
          maxX == other.maxX &&
          minY == other.minY &&
          maxY == other.maxY &&
          nPoints == other.nPoints;
}
